use_frameworks!

platform :ios, '8.0'

target 'StorageProject_Example' do
  pod 'StorageProject', :path => '../'

  target 'StorageProject_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
